### PR TITLE
Threads support

### PR DESCRIPTION
**Pull request by Airyzz**

### CODE REVIEW

**Comment by Airyzz** [comment]
Need to limit the number of lines that can be in the thread preview

**Comment by Airyzz** [comment]
I also haven't handled decryption of events yet in e2ee rooms

**Comment by notramo** [comment]
> Need to limit the number of lines that can be in the thread preview

What about simply capping at e.g. 60 characters and appending an `…` if it's more? This can be later improved.

> I also haven't handled decryption of events yet in e2ee rooms

Is it planned to be implemented before release or the first release will only support it for unencrypted rooms?

**Comment by Airyzz** [comment]
> What about simply capping at e.g. 60 characters and appending an `…` if it's more? This can be later improved.

Yup, that's the plan

> Is it planned to be implemented before release or the first release will only support it for unencrypted rooms?

Yea I'll probably look in to it within a couple days, it shouldn't be too hard to get working I think

**Comment by notramo** [comment]
@Airyzz is there any nightly build to try out the feature before the next release?

**Pull request merged**
